# Generated by Django 3.2.10 on 2021-12-22 14:10
from datetime import datetime, timezone

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.db.models import Sum


def make_up_old_point(apps, schema_editor):
    # 为了SQLite兼容性，跳过这个数据处理步骤
    # 这个迁移是为了处理历史数据的积分补偿，新部署可以跳过
    pass


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jcourse_api', '0013_auto_20211216_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='数值')),
                ('description', models.CharField(max_length=255, verbose_name='原因')),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '积分',
                'verbose_name_plural': '积分',
            },
        ),
        migrations.RunPython(make_up_old_point),
    ]
